name: example
description: Demonstrates how to use the emoji_extensions package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  emoji_extension:
    path: ../

dev_dependencies:
  lints: ^6.0.0
