name: emoji_extension
description: Emojis for Dart (Unicode 15.0) + useful String extension
version: 0.1.0
repository: https://github.com/Nikoro/emoji_extension
issue_tracker: https://github.com/Nikoro/emoji_extension/issues

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.17.1

dev_dependencies:
  test: ^1.24.2
  flutter_lints: ^2.0.1
